// SignIn Action types
const SIGNIN_INPUT_CHANGED = "SIGNIN_INPUT_CHANGED"
const SIGNIN_SUCCESS = "SIGNIN_SUCCESS"
const SIGNIN_FAILURE = "SIGNIN_FAILURE"
const SIGNIN_WAITTING = "SIGNIN_WAITTING"
const SIGNIN_CLEAR_PROPS = "SIGNIN_CLEAR_PROPS"
// SignUp Action types
const SIGNUP_INPUT_CHANGED = "SIGNUP_INPUT_CHANGED"
const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
const SIGNUP_FAILURE = "SIGNUP_FAILURE"
const SIGNUP_CLEAR_PROPS = "SIGNUP_CLEAR_PROPS"

const ActionTypes = {
    // SignIn
    SIGNIN_SUCCESS,
    SIGNIN_FAILURE,
    SIGNIN_INPUT_CHANGED,
    SIGNIN_WAITTING,
    SIGNIN_CLEAR_PROPS,
    // SignUp
    SIGNUP_INPUT_CHANGED,
    SIGNUP_FAILURE,
    SIGNUP_SUCCESS,
    SIGNUP_CLEAR_PROPS
}
export default ActionTypes;