const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const AUTHENTICATION = "AUTHENTICATION"
const AUTHEN_FAIL = "AUTHEN_FAIL"
const AUTHEN_SUCCESS = "AUTHEN_SUCCESS"
const USERNAME_CHANGED = "USERNAME_CHANGED"
const PASSWORD_CHANGED = "PASSWORD_CHANGED"
const ActionTypes = {
    LOGIN_SUCCESS,
    AUTHENTICATION,
    USERNAME_CHANGED,
    PASSWORD_CHANGED,
    AUTHEN_SUCCESS,
    AUTHEN_FAIL
}
export default ActionTypes;