// SignIn Action types
const SIGNIN_INPUT_CHANGED = "SIGNIN_INPUT_CHANGED"
const SIGNIN_SUCCESS = "SIGNIN_SUCCESS"
const SIGNIN_FAILURE = "SIGNIN_FAILURE"
const SIGNIN_CLEAR_PROPS = "SIGNIN_CLEAR_PROPS"
// Forgot pass Action types
const FORGOT_PASSWORD = "FORGOT_PASSWORD"
const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"
const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE"
// Change password Action types
const CHANGE_PASS_INPUT_CHANGE = "CHANGE_PASS_INPUT_CHANGE"
const CHANGE_PASS_SUCCESS = "CHANGE_PASS_SUCCESS"
const CHANGE_PASS_FAILURE = "CHANGE_PASS_FAILURE"
const CHANGE_PASS_CLEAR_PROPS ="CHANGE_PASS_CLEAR_PROPS"
// SignUp Action types
const SIGNUP_INPUT_CHANGED = "SIGNUP_INPUT_CHANGED"
const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
const SIGNUP_FAILURE = "SIGNUP_FAILURE"
const SIGNUP_CLEAR_PROPS = "SIGNUP_CLEAR_PROPS"
// Home Action types
const COMINGSOON_GET_MOVIE_FAILURE = "COMINGSOON_GET_MOVIE_FAILURE"
const COMINGSOON_GET_MOVIE_SUCCESS = "COMINGSOON_GET_MOVIE_SUCCESS"
const NOWSHOWING_GET_MOVIE_FAILURE = "NOWSHOWING_GET_MOVIE_FAILURE"
const NOWSHOWING_GET_MOVIE_SUCCESS = "NOWSHOWING_GET_MOVIE_SUCCESS"
// Movie Action types
const MOVIE_GET_DETAIL_SUCCESS = "MOVIE_GET_DETAIL_SUCCESS"
const MOVIE_GET_DETAIL_FAILURE = "MOVIE_GET_DETAIL_FAILURE"
const MOVIE_CLEAR_PROPS = "MOVIE_CLEAR_PROPS"
// Cineame Action types
const CITIES_GET_SUCCESS = "CITIES_GET_SUCCESS"
const CITIES_GET_FAILURE = "CITIES_GET_FAILURE"
const CINEMA_GET_SUCCESS = "CINEMA_GET_SUCCESS"
const CINEMA_GET_FAILURE = "CINEMA_GET_FAILURE"
const CINEMA_GET_SEAT_MAP_SUCCESS = "CINEMA_GET_SEAT_MAP_SUCCESS"
const CINEMA_GET_SEAT_MAP_FAILURE = "CINEMA_GET_SEAT_MAP_FAILURE"
const CINEMA_CLEAR_PROPS = "CINEMA_CLEAR_PROPS"
// Booking Action types 
const BOOKING_SHOWTIMES_LIST_FAILURE = "BOOKING_SHOWTIMES_LIST_FAILURE"
const BOOKING_SHOWTIMES_LIST_SUCCESS = "BOOKING_SHOWTIMES_LIST_SUCCESS"
const BOOKING_SET_MOVIE_ID = "BOOKING_SET_MOVIE_ID"
const BOOKING_SET_CINEMA_ID = "BOOKING_SET_CINEMA_ID"
const BOOKING_SET_DATE = "BOOKING_SET_DATE"
const BOOKING_SET_SHOWTIME_ID  = "BOOKING_SET_SHOWTIME_ID"
const BOOKING_CLEAR_PROPS = "BOOKING_CLEAR_PROPS"
const BOOKING_CHOOSE_SEAT = "BOOKING_CHOOSE_SEAT"
const BOOKING = "BOOKING"
// user
const USER_GET_PROFILE = "USER_GET_PROFILE"
const USER_GET_PROFILE_FAILURE = "USER_GET_PROFILE_FAILURE"
const USER_GET_PROFILE_SUCCESS = "USER_GET_PROFILE_SUCCESS"


const ActionTypes = {
    // SignIn
    SIGNIN_SUCCESS,
    SIGNIN_FAILURE,
    SIGNIN_INPUT_CHANGED,
    SIGNIN_CLEAR_PROPS,
    // Forgot Password
    FORGOT_PASSWORD,
    FORGOT_PASSWORD_FAILURE,
    FORGOT_PASSWORD_SUCCESS,
    // Change Password
    CHANGE_PASS_FAILURE,
    CHANGE_PASS_SUCCESS,
    CHANGE_PASS_INPUT_CHANGE,
    CHANGE_PASS_CLEAR_PROPS,
    // SignUp
    SIGNUP_INPUT_CHANGED,
    SIGNUP_FAILURE,
    SIGNUP_SUCCESS,
    SIGNUP_CLEAR_PROPS,
    // Home Action types
    COMINGSOON_GET_MOVIE_FAILURE,
    COMINGSOON_GET_MOVIE_SUCCESS,
    NOWSHOWING_GET_MOVIE_FAILURE,
    NOWSHOWING_GET_MOVIE_SUCCESS,
    // Movie Action types
    MOVIE_GET_DETAIL_FAILURE,
    MOVIE_GET_DETAIL_SUCCESS,
    MOVIE_CLEAR_PROPS,
    // Cineame Actin types
    CITIES_GET_FAILURE,
    CITIES_GET_SUCCESS,
    CINEMA_GET_FAILURE,
    CINEMA_GET_SUCCESS,
    CINEMA_GET_SEAT_MAP_FAILURE,
    CINEMA_GET_SEAT_MAP_SUCCESS,
    CINEMA_CLEAR_PROPS,
    // Booking Action types 
    BOOKING_SHOWTIMES_LIST_FAILURE,
    BOOKING_SHOWTIMES_LIST_SUCCESS,
    BOOKING_SET_CINEMA_ID,
    BOOKING_SET_DATE,
    BOOKING_SET_MOVIE_ID,
    BOOKING_SET_SHOWTIME_ID,
    BOOKING_CLEAR_PROPS,
    BOOKING_CHOOSE_SEAT,
    BOOKING,
    // User
    USER_GET_PROFILE,
    USER_GET_PROFILE_SUCCESS,
    USER_GET_PROFILE_FAILURE


}
export default ActionTypes;