const DataTypes = {
    ACTION_NAME: "ACTION_NAME",

    SIGNIN_SUBMIT: "SIGNIN_SUBMIT",

    SIGNOUT: "SIGNOUT",

    SIGNIN_INPUT_CHANGED: "SIGNIN_INPUT_CHANGED",

    LOGIN_SUCCESS: "LOGIN_SUCCESS",

    LOGIN_FAILURE: "LOGIN_FAILURE"
};

export default DataTypes;
